### ISSUE TITLE
File deleting is broken

### ISSUE THREAD

**Issue by ericfranz** [OSC/ood-fileexplorer#156]
1. Select a file
2. Click delete
3. Nothing happens and it is busy signal

Immediate steps:

1. I'm going to revert the production at OSC to 1.3.3.
2. We should revert the change we made to the dependency and implement the right change instead. 
   1. There should be no silent delete. Always ask the user. (i.e. shift + delete?)
   2. If there is no selection, display the warning that is supposed to be seen when pressing delete: no files selected.

**Comment by brianmcmichael** [comment]
Did you do a hard refresh of your assets?

**Comment by ericfranz** [comment]
That should not be required.

**Comment by ericfranz** [comment]
Reproduced in incognito mode.

**Comment by brianmcmichael** [comment]
Ok, I understand the issue. The current solution is the right direction, but there's a block in [operation.js](https://github.com/OSC/cloudcmd/blob/osc-5.3.1/lib/client/operation.js#L320-L324) that responds differently when one file is selected instead of multiple files.

We can revert back to the removal of the silent delete at https://github.com/OSC/cloudcmd/commit/301bea09059944f1d7c0c17d62f96eb64898ba4c

We can then update this https://github.com/OSC/cloudcmd/blob/osc-5.3.1/lib/client/operation.js#L275 to perform additional checking against null. Right now, if no items are selected `cloudcmd` will not process this block correctly.

**Comment by brianmcmichael** [comment]
This has been resolved in `v1.3.5`
